// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalDB.Services;

#nullable disable

namespace PortalDB.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20251008063243_UpdatedSystemUsers")]
    partial class UpdatedSystemUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalDB.Entities.Account.SystemUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(20)
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserCreatedAt");

                    b.Property<byte[]>("EmailEncrypted")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("SystemUserEmail");

                    b.Property<byte[]>("EntraIdEncrypted")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("MicrosoftEntraId");

                    b.Property<byte[]>("FirstNameEncrypted")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("SystemUserFirstName");

                    b.Property<bool>("IsActive")
                        .HasMaxLength(1)
                        .HasColumnType("bit")
                        .HasColumnName("SystemUserIsActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasMaxLength(20)
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserLastLoginAt");

                    b.Property<byte[]>("LastNameEncrypted")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("SystemUserLastName");

                    b.HasKey("Id");

                    b.ToTable("SystemUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
