// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalDB.Services;

#nullable disable

namespace PortalDB.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20251020064739_CreateSystemUserView")]
    partial class CreateSystemUserView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblOneTimePassword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OneTimePasswordId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("OneTimePasswordCreatedAt");

                    b.Property<string>("OTPEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OneTimePasswordOTP");

                    b.Property<long>("SystemUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("OneTimePasswordValidUntil");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("tblOneTimePasswords", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSessionToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SessionTokenId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SessionTokenCreatedAt");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SessionTokenKey");

                    b.Property<long>("SystemUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("SessionTokenValidUntil");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("tblSessionTokens", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemRoleCreatedAt");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemRoleDescription");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("SystemRoleIsActive");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemRoleName");

                    b.HasKey("Id");

                    b.ToTable("tblSystemRoles", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserCreatedAt");

                    b.Property<long>("DivisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("DivisionId");

                    b.Property<string>("EmailEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserEmail");

                    b.Property<string>("EntraIdEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MicrosoftEntraId");

                    b.Property<string>("FirstNameEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserFirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("SystemUserIsActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserLastLoginAt");

                    b.Property<string>("LastNameEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserLastName");

                    b.Property<long>("OfficeId")
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserStatusId");

                    b.Property<long?>("SystemRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.HasKey("Id");

                    b.ToTable("tblSystemUsers", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemUserStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserStatusId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserCreatedAt");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserStatusName");

                    b.HasKey("Id");

                    b.ToTable("tblSystemUserStatuses", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.VwSystemUser", b =>
                {
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserCreatedAt");

                    b.Property<string>("DivisionACronym")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DivisionAcronym");

                    b.Property<long>("DivisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("DivisionId");

                    b.Property<string>("DivisionName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DivisionName");

                    b.Property<string>("EmailEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserEmail");

                    b.Property<string>("FirstNameEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserFirstName");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("SystemUserIsActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserLastLoginAt");

                    b.Property<string>("LastNameEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserLastName");

                    b.Property<string>("OfficeAcronym")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OfficeAcronym");

                    b.Property<long>("OfficeId")
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    b.Property<string>("OfficeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OfficeName");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserStatusId");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserStatusName");

                    b.Property<long?>("SystemRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.Property<string>("SystemRoleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemRoleName");

                    b.ToTable("vwSystemUsers", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("dbo.vwSystemUsers", (string)null);
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.Division.TblDivision", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("DivisionId");

                    b.Property<string>("Acronym")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("DivisionAcronym");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DivisionName");

                    b.Property<long>("OfficeId")
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("tblDivisions", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.TblOffice", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    b.Property<string>("Acronym")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("OfficeAcronym");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OfficeName");

                    b.HasKey("Id");

                    b.ToTable("tblOffices", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.LOG.AuditTrail.TblAuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditTrailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AuditTrailAction");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("AuditTrailChangedAt");

                    b.Property<long?>("ChangedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("AuditTrailChangedBySystemUserId");

                    b.Property<byte[]>("ChangesEncrypted")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("AuditTrailChanges");

                    b.Property<long?>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("AuditTrailRecordId");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AuditTrailTableName");

                    b.HasKey("Id");

                    b.ToTable("tblAuditTrails", "log");
                });

            modelBuilder.Entity("PortalDB.Entities.LOG.TblErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ErrorLogId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ErrorLogCreatedAt");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ErrorLogDescription");

                    b.Property<string>("File")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ErrorLogFile");

                    b.Property<string>("Line")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ErrorLogLine");

                    b.HasKey("Id");

                    b.ToTable("tblErrorLogs", "log");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblOneTimePassword", b =>
                {
                    b.HasOne("PortalDB.Entities.DBO.Account.TblSystemUser", "SystemUser")
                        .WithMany("OneTimePassword")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSessionToken", b =>
                {
                    b.HasOne("PortalDB.Entities.DBO.Account.TblSystemUser", "SystemUser")
                        .WithMany("TblSessionToken")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.Division.TblDivision", b =>
                {
                    b.HasOne("PortalDB.Entities.DBO.Office.TblOffice", "Office")
                        .WithMany("Divisions")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemUser", b =>
                {
                    b.Navigation("OneTimePassword");

                    b.Navigation("TblSessionToken");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.TblOffice", b =>
                {
                    b.Navigation("Divisions");
                });
#pragma warning restore 612, 618
        }
    }
}
