// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalDB.Services;

#nullable disable

namespace PortalDB.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20251107074058_UpdatedScopeModule")]
    partial class UpdatedScopeModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblOneTimePassword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OneTimePasswordId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("OneTimePasswordCreatedAt");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("OneTimePasswordIsDeleted");

                    b.Property<string>("OTPEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OneTimePasswordOTP");

                    b.Property<long>("SystemUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("OneTimePasswordValidUntil");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("tblOneTimePasswords", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSessionToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SessionTokenId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SessionTokenCreatedAt");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("SessionTokenIsDeleted");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SessionTokenKey");

                    b.Property<long>("SystemUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("SessionTokenValidUntil");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("tblSessionTokens", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemRoleCreatedAt");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemRoleDescription");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("SystemRoleIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("SystemRoleIsDeleted");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemRoleName");

                    b.HasKey("Id");

                    b.ToTable("tblSystemRoles", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemRoleScope", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleScopeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemRoleScopeCreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("SystemRoleScopeIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("SystemRoleScopeIsDeleted");

                    b.Property<long?>("ModuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemModuleId");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.HasKey("Id");

                    b.ToTable("tblSystemRoleScopes", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserCreatedAt");

                    b.Property<long?>("DivisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("DivisionId");

                    b.Property<string>("EmailEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserEmail");

                    b.Property<string>("EmployeeIdEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserEmployeeId");

                    b.Property<long?>("EmploymentTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("EmploymentTypeId");

                    b.Property<long>("EntraId")
                        .HasColumnType("bigint")
                        .HasColumnName("MicrosoftEntraId");

                    b.Property<string>("FirstNameEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserFirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("SystemUserIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("SystemUserIsDeleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserLastLoginAt");

                    b.Property<string>("LastNameEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserLastName");

                    b.Property<long?>("OfficeId")
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    b.Property<long?>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("PositionId");

                    b.Property<long?>("ProfilePictureFileStorageId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserProfilePictureFileStorageId");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserStatusId");

                    b.Property<long?>("SystemRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.HasKey("Id");

                    b.ToTable("tblSystemUsers", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemUserStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserStatusId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserCreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("SystemUserStatusIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("SystemUserStatusIsDeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserStatusName");

                    b.HasKey("Id");

                    b.ToTable("tblSystemUserStatuses", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.VwSystemUser", b =>
                {
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserCreatedAt");

                    b.Property<string>("DivisionAcronym")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DivisionAcronym");

                    b.Property<long?>("DivisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("DivisionId");

                    b.Property<string>("DivisionName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DivisionName");

                    b.Property<string>("EmailEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserEmail");

                    b.Property<string>("EmployeeIdEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserEmployeeId");

                    b.Property<long?>("EmploymentTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("EmploymentTypeId");

                    b.Property<string>("EmploymentTypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentTypeName");

                    b.Property<string>("FirstNameEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserFirstName");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("SystemUserIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("SystemUserIsDeleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserLastLoginAt");

                    b.Property<string>("LastNameEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserLastName");

                    b.Property<string>("OfficeAcronym")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OfficeAcronym");

                    b.Property<long?>("OfficeId")
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    b.Property<string>("OfficeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OfficeName");

                    b.Property<long?>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("PositionId");

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PositionName");

                    b.Property<string>("ProfilePictureFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserProfilePictureOriginalFileName");

                    b.Property<long?>("ProfilePictureFileStorageId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserProfilePictureFileStorageId");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserStatusId");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserStatusName");

                    b.Property<long?>("SystemRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.Property<string>("SystemRoleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemRoleName");

                    b.ToTable("vwSystemUsers", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("vwSystemUsers", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Module.TblSystemModule", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemModuleId");

                    b.Property<string>("Acronym")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemModuleAcronym");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemModuleCreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("SystemModuleIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("SystemModuleIsDeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemModuleName");

                    b.HasKey("Id");

                    b.ToTable("tblSystemModules", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Notification.TblSystemNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SystemNotificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemNotificationCreatedAt");

                    b.Property<long?>("CreatedBySystemUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemNotificationBySystemUserId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemNotificationDescription");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("SystemNotificationIsDeleted");

                    b.Property<long?>("SystemUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemNotificationForSystemUserId");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemNotificationTitle");

                    b.HasKey("Id");

                    b.ToTable("tblSystemNotifications", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Notification.TblSystemNotificationRead", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SystemNotificationReadId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemNotificationReadCreatedAt");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("SystemNotificationReadIsDeleted");

                    b.Property<long?>("NotificationId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemNotificationId");

                    b.Property<long?>("SystemUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemNotificationReadBySystemUserId");

                    b.HasKey("Id");

                    b.ToTable("tblSystemNotificationReads", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.Division.TblDivision", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("DivisionId");

                    b.Property<string>("Acronym")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("DivisionAcronym");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DivisionCreatedAt");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DivisionIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("DivisionIsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DivisionName");

                    b.Property<long>("OfficeId")
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("tblDivisions", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.Division.VwDivision", b =>
                {
                    b.Property<string>("Acronym")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("DivisionAcronym");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DivisionCreatedAt");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("DivisionId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DivisionIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("DivisionIsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DivisionName");

                    b.Property<string>("OfficeAcronym")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OfficeAcronym");

                    b.Property<long>("OfficeId")
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    b.Property<string>("OfficeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OfficeName");

                    b.HasIndex("OfficeId");

                    b.ToTable("vwDivisions", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("vwDivisions", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.TblEmploymentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("EmploymentTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("EmploymentTypeCreatedAt");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("EmploymentTypeIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("EmploymentTypeIsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmploymentTypeName");

                    b.HasKey("Id");

                    b.ToTable("tblEmploymentTypes", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.TblOffice", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    b.Property<string>("Acronym")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("OfficeAcronym");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("OfficeCreatedAt");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("OfficeIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("OfficeIsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OfficeName");

                    b.HasKey("Id");

                    b.ToTable("tblOffices", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.TblPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PositionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Acronym")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PositionAcronym");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PositionCreatedAt");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("PositionIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("PositionIsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PositionName");

                    b.Property<string>("SalaryGrade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("PositionSalaryGrade");

                    b.HasKey("Id");

                    b.ToTable("tblPositions", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Storage.TblFileStorage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("FileStorageId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FileStorageBlobName");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FileStorageContentType");

                    b.Property<string>("FolderName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FileStorageFlatFolderName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("FileStorageIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("FileStorageIsDeleted");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FileStorageOriginalFileName");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FileStorageUploadedAt");

                    b.Property<long>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("FileStorageUploadedBy");

                    b.HasKey("Id");

                    b.ToTable("tblFileStorages", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.LOG.AuditTrail.TblAuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditTrailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AuditTrailAction");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("AuditTrailChangedAt");

                    b.Property<long?>("ChangedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("AuditTrailChangedBySystemUserId");

                    b.Property<byte[]>("ChangesEncrypted")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("AuditTrailChanges");

                    b.Property<long?>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("AuditTrailRecordId");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AuditTrailTableName");

                    b.HasKey("Id");

                    b.ToTable("tblAuditTrails", "log");
                });

            modelBuilder.Entity("PortalDB.Entities.LOG.TblActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivityLogId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ActivityLogSpecificAction");

                    b.Property<long?>("ActionBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ActivityLogActionBy");

                    b.Property<long?>("AuditTrailId")
                        .HasColumnType("bigint")
                        .HasColumnName("ActivityLogConnectedAuditTrailId");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActivityLogCreatedAt");

                    b.HasKey("Id");

                    b.ToTable("tblActivityLogs", "log");
                });

            modelBuilder.Entity("PortalDB.Entities.LOG.TblErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ErrorLogId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ErrorLogCreatedAt");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ErrorLogDescription");

                    b.Property<string>("File")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ErrorLogFile");

                    b.Property<string>("Line")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ErrorLogLine");

                    b.HasKey("Id");

                    b.ToTable("tblErrorLogs", "log");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblOneTimePassword", b =>
                {
                    b.HasOne("PortalDB.Entities.DBO.Account.TblSystemUser", "SystemUser")
                        .WithMany("OneTimePassword")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSessionToken", b =>
                {
                    b.HasOne("PortalDB.Entities.DBO.Account.TblSystemUser", "SystemUser")
                        .WithMany("TblSessionToken")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.Division.TblDivision", b =>
                {
                    b.HasOne("PortalDB.Entities.DBO.Office.TblOffice", "Office")
                        .WithMany("Divisions")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.Division.VwDivision", b =>
                {
                    b.HasOne("PortalDB.Entities.DBO.Office.TblOffice", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemUser", b =>
                {
                    b.Navigation("OneTimePassword");

                    b.Navigation("TblSessionToken");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.TblOffice", b =>
                {
                    b.Navigation("Divisions");
                });
#pragma warning restore 612, 618
        }
    }
}
