// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalDB.Services;

#nullable disable

namespace PortalDB.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    partial class PortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblOneTimePassword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OneTimePasswordId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("OneTimePasswordCreatedAt");

                    b.Property<string>("OTPEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OneTimePasswordOTP");

                    b.Property<long>("SystemUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("OneTimePasswordValidUntil");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("tblOneTimePasswords", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SystemUserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserCreatedAt");

                    b.Property<string>("EmailEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserEmail");

                    b.Property<string>("EntraIdEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MicrosoftEntraId");

                    b.Property<string>("FirstNameEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserFirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("SystemUserIsActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SystemUserLastLoginAt");

                    b.Property<string>("LastNameEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SystemUserLastName");

                    b.HasKey("Id");

                    b.ToTable("tblSystemUsers", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.Division.TblDivision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DivisionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Acronym")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("DivisionAcronym");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DivisionName");

                    b.Property<long>("OfficeId")
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("tblDivisions", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.TblOffice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OfficeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Acronym")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("OfficeAcronym");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OfficeName");

                    b.HasKey("Id");

                    b.ToTable("tblOffices", "dbo");
                });

            modelBuilder.Entity("PortalDB.Entities.LOG.AuditTrail.TblAuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditTrailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AuditTrailAction");

                    b.Property<DateTime?>("ChangedAt")
                        .HasMaxLength(20)
                        .HasColumnType("datetime2")
                        .HasColumnName("AuditTrailChangedAt");

                    b.Property<long?>("ChangedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("AuditTrailChangedBySystemUserId");

                    b.Property<byte[]>("ChangesEncrypted")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("AuditTrailChanges");

                    b.Property<long?>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("AuditTrailRecordId");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AuditTrailTableName");

                    b.HasKey("Id");

                    b.ToTable("tblAuditTrails", "log");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblOneTimePassword", b =>
                {
                    b.HasOne("PortalDB.Entities.DBO.Account.TblSystemUser", "SystemUser")
                        .WithMany("OneTimePassword")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.Division.TblDivision", b =>
                {
                    b.HasOne("PortalDB.Entities.DBO.Office.TblOffice", "Office")
                        .WithMany("Divisions")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Account.TblSystemUser", b =>
                {
                    b.Navigation("OneTimePassword");
                });

            modelBuilder.Entity("PortalDB.Entities.DBO.Office.TblOffice", b =>
                {
                    b.Navigation("Divisions");
                });
#pragma warning restore 612, 618
        }
    }
}
