import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';

interface NumberInputModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirm: (number: string) => void;
  defaultYear?: number;
  defaultMonth?: number;
  defaultSequence?: string;
  defaultNumber?: string;
  label: string;
}

export function NumberInputModal({ isOpen, onClose, onConfirm, defaultYear, defaultMonth, defaultSequence, defaultNumber, label }: NumberInputModalProps) {
  const currentYear = new Date().getFullYear();
  const years = Array.from({ length: 6 }, (_, i) => currentYear - 2 + i); // 2 years before, 3 after
  const months = [
    { value: 1, label: 'January' },
    { value: 2, label: 'February' },
    { value: 3, label: 'March' },
    { value: 4, label: 'April' },
    { value: 5, label: 'May' },
    { value: 6, label: 'June' },
    { value: 7, label: 'July' },
    { value: 8, label: 'August' },
    { value: 9, label: 'September' },
    { value: 10, label: 'October' },
    { value: 11, label: 'November' },
    { value: 12, label: 'December' },
  ];

  // Parse defaultNumber if provided, format: YYYY-MM-SEQ
  let initialYear = defaultYear || currentYear;
  let initialMonth = defaultMonth || new Date().getMonth() + 1;
  let initialSequence = defaultSequence || '';
  if (defaultNumber) {
    const match = defaultNumber.match(/^(\d{4})-(\d{2})-(\d{3,})$/);
    if (match) {
      initialYear = Number(match[1]);
      initialMonth = Number(match[2]);
      initialSequence = match[3];
    }
  }

  const [year, setYear] = useState(initialYear);
  const [month, setMonth] = useState(initialMonth);
  const [sequence, setSequence] = useState(initialSequence);

  const autogenerated = `${year}-${String(month).padStart(2, '0')}-${sequence.padStart(3, '0')}`;

  const handleConfirm = () => {
    if (!sequence.trim()) return;
    onConfirm(autogenerated);
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>{label}</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Year</label>
          <select
            className="w-full border rounded px-2 py-1"
            value={year}
            onChange={e => setYear(Number(e.target.value))}
          >
            {years.map(y => (
              <option key={y} value={y}>{y}</option>
            ))}
          </select>
          <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Month</label>
          <select
            className="w-full border rounded px-2 py-1"
            value={month}
            onChange={e => setMonth(Number(e.target.value))}
          >
            {months.map(m => (
              <option key={m.value} value={m.value}>{m.label}</option>
            ))}
          </select>
          <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Sequence</label>
          <Input
            value={sequence}
            onChange={e => setSequence(e.target.value.replace(/\D/g, ''))}
            placeholder="Enter sequence number"
            autoFocus
          />
          <div className="mt-2 text-xs text-slate-500">Autogenerated: <span className="font-mono bg-slate-100 px-2 py-1 rounded">{autogenerated}</span></div>
        </div>
        <DialogFooter className="gap-2 pt-4">
          <Button variant="outline" onClick={onClose}>Cancel</Button>
          <Button onClick={handleConfirm}>Confirm</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
