import { TagPreview, TagTemplate } from "@/hooks/useAssetTagging";

type TagUser = { firstName?: string | null };

interface TagPreviewGridProps {
  tagPreviews: TagPreview[];
  includeQR: boolean;
  includeLogo: boolean;
  activeTemplate: TagTemplate;
  generatedBy?: TagUser | null;
  logoSrc: string;
}

export function TagPreviewGrid({ tagPreviews, includeQR, includeLogo, activeTemplate, generatedBy, logoSrc }: TagPreviewGridProps) {
  if (!tagPreviews.length) return null;

  return (
    <div className="print-area">
      <div className="grid gap-3 sm:grid-cols-2 md:grid-cols-3 print:gap-2">
        {tagPreviews.map((tag) => (
          <div
            key={tag.id}
            className="border rounded-md shadow-sm p-3 bg-white flex flex-col gap-2"
            style={{ width: `${activeTemplate.width}mm`, height: `${activeTemplate.height}mm` }}
          >
            <div className="flex items-center justify-between gap-2">
              {includeLogo && <img src={logoSrc} alt="ERC Logo" className="h-6 w-6" />}
              <div className="text-right">
                <p className="text-[10px] font-semibold">{tag.code}</p>
                <p className="text-[9px] text-slate-600">{tag.group}</p>
              </div>
            </div>

            <div className="text-[9px] leading-tight text-slate-700">
              <p className="font-semibold truncate">{tag.description}</p>
              <p className="text-[9px] text-slate-600 truncate">{tag.category}</p>
              <p className="text-[9px] text-slate-600 truncate">{tag.location}</p>
              <p className="text-[9px] text-slate-600 truncate">{tag.assignedTo}</p>
            </div>

            {includeQR && tag.qrCode ? (
              <div className="flex items-center gap-2 mt-auto">
                <img src={tag.qrCode} alt={`QR for ${tag.code}`} className="h-14 w-14" />
                <div className="text-[8px] text-slate-600 leading-tight">
                  <p>Scan for details</p>
                  <p>Generated by {generatedBy?.firstName || "System"}</p>
                </div>
              </div>
            ) : (
              <p className="text-[8px] text-slate-600">QR code disabled</p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
